# Generated by Django 4.2.7 on 2023-11-13 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plumberz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('Service_date', models.DateField(auto_now=True)),
                ('Special_request', models.TextField(max_length=7000)),
                ('Choose_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumberz.services')),
            ],
            options={
                'verbose_name_plural': 'booking',
            },
        ),
    ]
