# Generated by Django 4.2.7 on 2023-11-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumberz', '0002_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Special_request',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Choose_service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Service_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='date_field',
            field=models.CharField(default='ewertyui', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('service 1', 'service 1'), ('service 2', 'service 2'), ('service 3', 'service 3')], default='service 2', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(help_text='Insert a valid email', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
