# Generated by Django 4.2.7 on 2023-11-15 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plumberz', '0003_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_field',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('1', 'service 1'), ('2', 'service 2'), ('3', 'service 3')], max_length=10),
        ),
    ]
