# Generated by Django 4.2.7 on 2023-11-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumberz', '0004_remove_booking_date_field_booking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headline', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('content', models.TextField(max_length=100000)),
            ],
        ),
    ]
