# Generated by Django 4.2.7 on 2023-11-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumberz', '0005_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('1', 'service 1'), ('2', 'service 2'), ('3', 'service 3')])),
                ('date', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(),
        ),
    ]
