# Generated by Django 4.2.7 on 2023-11-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plumberz', '0006_contactform_alter_booking_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactform',
        ),
    ]
