# Generated by Django 4.2.7 on 2023-11-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumberz', '0007_delete_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('emails', models.EmailField(max_length=254)),
                ('services', models.CharField(max_length=200)),
                ('dates', models.CharField(max_length=200)),
                ('messages', models.TextField()),
            ],
        ),
    ]
