# Generated by Django 4.2.7 on 2023-12-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumberz', '0008_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='dates',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
