# Generated by Django 4.2.7 on 2023-12-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumberz', '0009_alter_booking_date_alter_contactform_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(),
        ),
    ]
